# Config file for Quest 64 Recompilation

[input]
entrypoint = 0x80000400
# Paths are relative to the location of this config file.
# elf_path = "quest64.elf"
rom_file_path = "quest64.us.z64"
symbols_file_path = "Quest64Syms/dump.toml"
output_func_path = "RecompiledFuncs"

[patches]
stubs = [
    "func_800471B0", #some libleo function
    "func_8004793C", #another libleo function
    "initPFSPaks", #is this ever actually called??
    "func_8003C530",
]

ignored = [
    "__osBlockSum",
    "__osPfsReleasePages",
    "__osPfsDeclearPage",
]

[[patches.hook]]
func = "func_800314C0"
before_vram = 0x800314C0
text = "extern void qs64_mod_tick(uint8_t*); qs64_mod_tick(rdram);"

[[patches.hook]]
func = "func_80001800"
before_vram = 0x800020AC
text = "extern void qs64_mod_finish_warp(uint8_t*); qs64_mod_finish_warp(rdram);"

[[patches.hook]]
func = "func_80002F60"
before_vram = 0x80002F60
text = "extern void qs64_mod_player_tick(uint8_t*); qs64_mod_player_tick(rdram);"

[[patches.hook]]
func = "func_800027D0"
before_vram = 0x800027D0
text = "extern void qs64_mod_reset(uint8_t*); qs64_mod_reset(rdram);"

[[patches.hook]]
func = "func_80024690"
text = "load_overlays(ctx->r4, ctx->r5, ctx->r6);"
before_vram = 0x80024690

[[patches.hook]]
func = "dma_write"
text = "load_overlays(ctx->r4, ctx->r5, ctx->r6);"
before_vram = 0x80024260
